import { memo } from 'react';
import type { TokenUsage } from '../types';

const SCENARIO_FIELDS = [
  { field: 'id',              type: 'string',   description: 'Unique identifier, e.g. SCN-001' },
  { field: 'title',           type: 'string',   description: 'Short descriptive title' },
  { field: 'type',            type: 'enum',     description: 'HP | AF | EC | EG | BR' },
  { field: 'requirementRefs', type: 'string[]', description: 'Requirement IDs this scenario covers' },
  { field: 'preconditions',   type: 'string[]', description: 'State required before test execution' },
  { field: 'flow',            type: 'string[]', description: 'Step-by-step test flow' },
  { field: 'expectedOutcome', type: 'string',   description: 'Expected result after execution' },
  { field: 'priority',        type: 'enum',     description: 'Critical | High | Medium | Low' },
];

const TESTCASE_FIELDS = [
  { field: 'id',             type: 'string',  description: 'Unique identifier, e.g. TC-001' },
  { field: 'title',          type: 'string',  description: 'Short descriptive title' },
  { field: 'scenarioId',     type: 'string',  description: 'Parent scenario reference' },
  { field: 'requirementRefs',type: 'string[]',description: 'Requirement IDs covered' },
  { field: 'gherkin',        type: 'string',  description: 'Given/When/Then BDD syntax' },
  { field: 'preconditions',  type: 'string[]',description: 'State required before test' },
  { field: 'steps',          type: 'string[]',description: 'Numbered execution steps' },
  { field: 'expectedResult', type: 'string',  description: 'Expected outcome after steps' },
  { field: 'testData',       type: 'string',  description: 'Sample data used during test' },
  { field: 'layer',          type: 'enum',    description: 'Unit | API | UI' },
  { field: 'priority',       type: 'enum',    description: 'Critical | High | Medium | Low' },
];

const FieldTable = ({ fields }: { fields: typeof SCENARIO_FIELDS }): JSX.Element => (
  <div className="table-wrap">
    <table className="table">
      <thead>
        <tr>
          <th>Field</th>
          <th>Type</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {fields.map(({ field, type, description }) => (
          <tr key={field}>
            <td style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-xs)', fontWeight: 600 }}>{field}</td>
            <td><span className="scn-badge scn-badge--af">{type}</span></td>
            <td style={{ color: 'var(--text-secondary)', fontSize: 'var(--text-sm)' }}>{description}</td>
          </tr>
        ))}
      </tbody>
    </table>
  </div>
);

export const OutputTab = memo(function OutputTab({ tokenUsage }: { tokenUsage?: TokenUsage | null }): JSX.Element {
  return (
    <section className="panel">
      <h2>Output Schema</h2>
      <p className="helper-text">
        Reference for the data structures generated by TraceLMs Cloud. Export options are available
        on the Test Cases and Automation tabs after generation.
      </p>

      {tokenUsage && (
        <div className="token-summary-card">
          <div className="token-summary-title">Last Generation — Token Usage</div>
          <div className="token-summary-grid">
            <div className="token-stat">
              <span className="token-stat-value">{tokenUsage.totalTokens.toLocaleString()}</span>
              <span className="token-stat-label">Total</span>
            </div>
            <div className="token-stat">
              <span className="token-stat-value">{tokenUsage.promptTokens.toLocaleString()}</span>
              <span className="token-stat-label">Prompt</span>
            </div>
            <div className="token-stat">
              <span className="token-stat-value">{tokenUsage.completionTokens.toLocaleString()}</span>
              <span className="token-stat-label">Completion</span>
            </div>
          </div>
        </div>
      )}

      <h3 style={{ marginTop: 'var(--space-5)', marginBottom: 'var(--space-3)' }}>Test Scenario Fields</h3>
      <FieldTable fields={SCENARIO_FIELDS} />

      <h3 style={{ marginTop: 'var(--space-6)', marginBottom: 'var(--space-3)' }}>Test Case Fields</h3>
      <FieldTable fields={TESTCASE_FIELDS} />

      <div className="coming-soon-note" style={{ marginTop: 'var(--space-6)' }}>
        <span className="coming-soon-icon">📄</span>
        <div>
          <strong>Customisable Templates</strong>
          <p>Future release will allow field-level customisation — rename fields, toggle visibility,
          reorder columns, and define export column mappings for CSV/JSON downloads.</p>
        </div>
      </div>
    </section>
  );
});
